export const productCategories = [
  "all",
  "women",
  "men",
  "casual",
  "winter",
  "streetwear",
];

export const mockProducts = [
  {
    id: "p1",
    title: "Hoodies & Sweetshirt",
    category: "casual",
    price: 89,
    rating: 4.7,
    image: "/images/New-Arrival-Section/new-arrival-section-image1.png",
  },
  {
    id: "p2",
    title: "Coats & Parkas",
    category: "winter",
    price: 129,
    rating: 4.8,
    image: "/images/New-Arrival-Section/new-arrival-section-image2.png",
  },
  {
    id: "p3",
    title: "Tees & T-Shirt",
    category: "streetwear",
    price: 59,
    rating: 4.5,
    image: "/images/New-Arrival-Section/new-arrival-section-image3.png",
  },
  {
    id: "p4",
    title: "Trendy Crop Blazer",
    category: "women",
    price: 99,
    rating: 4.6,
    image: "/images/Youngs-Favourite-Section/young-favourite-image1.png",
  },
  {
    id: "p5",
    title: "Urban Knit Set",
    category: "women",
    price: 109,
    rating: 4.8,
    image: "/images/Youngs-Favourite-Section/young-favourite-image2.png",
  },
  {
    id: "p6",
    title: "Weekend Utility Jacket",
    category: "men",
    price: 119,
    rating: 4.4,
    image: "/images/New-Arrival-Section/new-arrival-section-image2.png",
  },
  {
    id: "p7",
    title: "Relaxed Fit Street Tee",
    category: "men",
    price: 49,
    rating: 4.3,
    image: "/images/New-Arrival-Section/new-arrival-section-image3.png",
  },
  {
    id: "p8",
    title: "Soft Oversized Hoodie",
    category: "women",
    price: 79,
    rating: 4.9,
    image: "/images/New-Arrival-Section/new-arrival-section-image1.png",
  },
];